version: '3.3'
services:

  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env

  web:
    build: .
    restart: always
    volumes:
      - media_value:/code/media/
    ports:
      - "8000:8000"
      - "8001:8001"
    expose:
      - 8000
      - 8001
    depends_on:
      - db

  nginx:
    image: nginx:1.19.8-alpine
    ports:
      - "80:80"
      - "443:443"
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - /etc/letsencrypt/:/etc/letsencrypt
      - ./yatube/static:/var/html/static/
      - ./yatube/media:/var/html/media/
    command: /bin/sh -c "nginx -g 'daemon off;'"
    depends_on:
      - web

  cache:
    image: redis:5
    user: root
    restart: unless-stopped
    ports:
      - '6379:6379'
    volumes:
      - cache:/data


volumes:
  postgres_data:
  static_value:
  media_value:
  cache:
