# Generated by Django 2.2.19 on 2021-07-18 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20210718_2006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='pub_date',
            field=models.DateField(verbose_name='Дата публикации поста'),
        ),
    ]
